M48
; DRILL file {KiCad 7.0.1} date Tue Mar  4 19:41:49 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-04T19:41:49-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.4362Y-3.2112
X4.4362Y-3.4022
T2
X4.5555Y-3.1994
X4.5555Y-3.414
T0
M30
